package:
  name: glibc
  version: 2.23

build:
  number: 3
  detect_binary_files_with_prefix: True

source:
  fn: glibc-2.23.tar.gz
  url: http://ftp.snt.utwente.nl/pub/software/gnu/glibc/glibc-2.23.tar.gz

about:
  home: http://www.gnu.org/software/libc/
  license: LGPL
  summary: "Any Unix-like operating system needs a C library: the library which defines the ``system calls'' and other basic facilities such as open, malloc, printf, exit..."
