about:
  brief: ''
  name: ''
authors:
  basename: AUTHORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  plugin: CeCILL-C
  width: 78
rst:
  plugin: default
version:
  plugin: semantic
