package:
  name: gmp
  version: "6.1.0"

source:
  fn: gmp-6.1.0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.bz2
  md5: 86ee6e54ebfc4a90b643a65e402c4048

build:
  number: 1

requirements:
  build:
    - m4

test:
  files:
    - test.c

about:
  home: http://gmplib.org/
  license: GPL 3
