package:
  name: isl
  version: "0.14"

source:
  fn: isl-0.14.tar.bz2
  url: ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.14.tar.bz2

build:
  number: 0
  skip: True  # [not unix]

requirements:
  build:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f "$PREFIX/lib/libisl.a"
    - test -f "$PREFIX/lib/libisl.la"
    - test -f "$PREFIX/lib/libisl.so"  # [linux]
    - test -f "$PREFIX/lib/libisl.dylib"  # [osx]
    - test -d "$PREFIX/include/isl"

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.
