package:
  name: statiskit-dev
  version: {{ DATETIME_DESCRIBE_VERSION }}

build:
  number: {{ DATETIME_DESCRIBE_NUMBER }}

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0
  summary: A meta-package containing all components of the StatisKit software suite and toolchains used to develop them

requirements:
  host:
    - libtoolchain
    - libtoolchain-dev
    - python-toolchain
    - autowig-toolchain
    # - libstatiskit_stl-dev
    # - libstatiskit_linalg-dev
    # - libstatiskit_core-dev
    # - libstatiskit_glm-dev
    # - python-statiskit
  run:
    - {{ pin_compatible('libtoolchain', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('libtoolchain-dev', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python-toolchain', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('autowig-toolchain', min_pin='x.x', max_pin='x.x') }}
    # - {{ pin_compatible('libstatiskit_stl-dev', min_pin='x.x', max_pin='x.x') }}
    # - {{ pin_compatible('libstatiskit_linalg-dev', min_pin='x.x', max_pin='x.x') }}
    # - {{ pin_compatible('libstatiskit_core-dev', min_pin='x.x', max_pin='x.x') }}
    # - {{ pin_compatible('libstatiskit_glm-dev', min_pin='x.x', max_pin='x.x') }}
    # - {{ pin_compatible('python-statiskit', min_pin='x.x', max_pin='x.x') }}