package:
  name: statiskit-toolchain
  version: {{ DATETIME_DESCRIBE_VERSION }}

build:
  number: {{ DATETIME_DESCRIBE_NUMBER }}

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0
  summary: A meta-package containing all components of the StatisKit software suite and toolchains used to develop them

requirements: 
  host:
    - libtoolchain-dev
    - libstatiskit-dev
    - libtoolchain
    - libstatiskit
    - python-toolchain
    - python-statiskit
    - autowig-toolchain
    - libstatiskit-wig                                       # [linux]
    - devops-tools
  run:
    - {{ pin_compatible('libtoolchain-dev', exact=True) }}
    - {{ pin_compatible('libstatiskit-dev', exact=True) }}
    - {{ pin_compatible('libtoolchain', exact=True) }}
    - {{ pin_compatible('libstatiskit', exact=True) }}
    - {{ pin_compatible('python-toolchain', exact=True) }}
    - {{ pin_compatible('python-statiskit', exact=True) }}
    - {{ pin_compatible('autowig-toolchain', exact=True) }}
    - {{ pin_compatible('libstatiskit-wig', exact=True) }}   # [linux]
    - {{ pin_compatible('devops-tools', exact=True) }}