package:
  name: statiskit-toolchain
  version: {{ DATETIME_DESCRIBE_VERSION }}

build:
  number: {{ DATETIME_DESCRIBE_NUMBER }}

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0
  summary: A meta-package containing all components of the StatisKit software suite and toolchains used to develop them

requirements: 
  host:
    - libstatiskit-dev
    - autowig-libstatiskit                                   # [linux]
    - libstatiskit
    - python-statiskit
    - devops-tools
  run:
    - {{ pin_compatible('libstatiskit-dev', exact=True) }}
    - {{ pin_compatible('autowig-statiskit', exact=True) }}  # [linux]
    - {{ pin_compatible('libstatiskit', exact=True) }}
    - {{ pin_compatible('python-statiskit', exact=True) }}
    - {{ pin_compatible('devops-tools', exact=True) }}