package:
  name: mpc
  version: "1.0.3"

source:
  fn: mpc-1.0.3.tar.gz
  url: http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz
  sha1: b8be66396c726fdc36ebb0f692ed8a8cca3bcc66

requirements:
  build:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

about:
  home: http://www.multiprecision.org/
  license: GPL
  summary: Gnu Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
