package:
  name: mpc
  version: "0.8.1"

source:
  fn: mpc-0.8.1.tar.gz
  url: ftp://gcc.gnu.org/pub/gcc/infrastructure/mpc-0.8.1.tar.gz

requirements:
  build:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

about:
  home: http://www.multiprecision.org/
  license: GPL
  summary: Gnu Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
