package:
  name: python-statiskit 
  version: {{ DATETIME_DESCRIBE_VERSION }}

build:
  number: {{ DATETIME_DESCRIBE_NUMBER }}

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0
  summary: A meta-package containing all Python packages of the StatisKit software suite

requirements:
  build:
    - python-toolchain
  host:
    - python-statiskit_stl
    - python-statiskit_linalg
    - python-statiskit_core
    - python-statiskit_glm
    # - python-statiskit_pgm
  run:
    - {{ pin_compatible('python-toolchain', exact=True) }}
    - {{ pin_compatible('python-statiskit_stl', exact=True) }}
    - {{ pin_compatible('python-statiskit_linalg', exact=True) }}
    - {{ pin_compatible('python-statiskit_core', exact=True) }}
    - {{ pin_compatible('python-statiskit_glm', exact=True) }}
    # - {{ pin_compatible('python-statiskit_pgm', exact=True) }}
    - python
    - ipython
    - jupyter
    - matplotlib
