package:
  name: python-statiskit 
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0
  summary: A meta-package containing all components of the StatisKit software suite

requirements:
  host:
    - python-statiskit_stl
    - python-statiskit_linalg
    - python-statiskit_core
    - python-statiskit_glm
  run:
    - {{ pin_compatible('python-statiskit_stl', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python-statiskit_linalg', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python-statiskit_core', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python-statiskit_glm', min_pin='x.x', max_pin='x.x') }}
    - python
    - ipython
    - jupyter
    - matplotlib
