# -*-python-*-

Import("env")

conda_env = env.Clone(tools = ['conda'])

sources = conda_env.Glob('*')

exclude = """
libboost
python-scons
""".split()

sources = [source for source in sources if not source.name in exclude]

targets = conda_env.CondaPackages(sources)
Alias("build", targets)

targets = conda_env.CondaEnvironment(sources)
Alias("install", targets)