# -*-python-*-

Import("env")

conda_env = env.Clone(tools = ['conda'])

exclude = """
""".split()

targets = conda_env.BuildConda(exclude=exclude)
Alias("build", targets)

targets = conda_env.InstallConda(exclude=exclude)
Alias("install", targets)