package:
  name: gcc
  version: 5.4.0

source:
  fn: gcc-5.4.0.tar.bz2
  url: http://mirrors.kernel.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
  md5: 4c626ac2a83ef30dfb9260e6f59c2b30

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: True  # [not unix]

requirements:
  build:
    # Dependencies that are required to unpack GCC sources:
    # * tar
    # * bzip2
    # System dependencies that are required to build GCC:
    # * gcc
    # * gcc-c++
    # * make
    # * zip
    # NOTE: Do not make gcc a conda build dependency (you will need to add it to the PATH manually)
    #
    # Other build requirements (https://gcc.gnu.org/install/prerequisites.html):
    - gmp >=6.1
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.17,<=0.17.1
  run:
    - gmp >=6.1
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.17,<=0.17.1

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
