package:
  name: linux-headers
  version: 2.6.32

build:
  number: 1
  detect_binary_files_with_prefix: True

source:
  fn: linux-4.4.1.tar.gz
  url: https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.4.1.tar.gz
  # patches:
  #   - patch-4.4.1

about:
  home: http://www.gnu.org/software/libc/
  license: LGPL
  summary: "Any Unix-like operating system needs a C library: the library which defines the ``system calls'' and other basic facilities such as open, malloc, printf, exit..."
