package:
  name: pypandoc
  version: "1.3.3"

source:
  fn: pypandoc-1.3.3.zip
  url: https://github.com/bebraw/pypandoc/archive/v1.3.3.zip
  sha1: e72e645b0776ac5e3e817b9fd1d3c635a2b21924

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pandoc
  run:
    - python
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"

about:
  home: https://github.com/bebraw/pypandoc
  license: MIT
  summary: 'Thin wrapper for "pandoc"'