package:
  name: python-gitpython
  version: "2.0.9"

source:
  fn: gitPython-2.0.9.tar.gz
  url: https://github.com/gitpython-developers/GitPython/archive/2.0.9.tar.gz

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - gitdb

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD license
  summary: 'GitPython is a python library used to interact with Git repositories.'
