package:
  name: python-gitpython
  version: "2.0.9"

source:
  path: https://pypi.python.org/packages/4b/f7/4ddb9678961c2284261bdfc94b02a04c7d1bc45a593414c2489e83e7b80e/GitPython-2.0.9.tar.gz

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD license
  summary: 'GitPython is a python library used to interact with Git repositories.'
