##################################################################################
#                                                                                #
# PkgTk: Tool kit for Python packages                                            #
#                                                                                #
# Homepage: pkgtk.readthedocs.io                                                 #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (11)                       #
#                                                                                #
##################################################################################

package:
    name: python-pkgtk
    version: "0.1.0"

source:
    path: ../..

build:
    number: 0
    preserve_egg_dir: True
  
about:
    home: http://pkgtk.readthedocs.org
    license: CeCILL-C

requirements:
    build:
        - python
        - pyyaml
    run:
        - python
        - pyyaml
        - gitpython
        - github3.py
        - path.py
        - python-parse
        - mako
    
test:
    requires:
        - nose
        - coverage
    commands:
        - cd {{ SRC_DIR }}
        - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=pkgtk
        - REPOSITORY_DIR=`readlink -e $RECIPE_DIR/../..` # [linux]
        - sed -i'' -e 's|'"$PREFIX"'/lib/python2.7/site-packages/PkgTk-0.0.0-py2.7.egg|'"$REPOSITORY_DIR"'/src/py|g' .coverage # [linux]
        - sed -i'' -e 's|'"$SRC_DIR"'|'"$REPOSITORY_DIR"'|g' .coverage # [linux]
        - mv .coverage $REPOSITORY_DIR # [linux]
