##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (26)                       #
#                                                                                #
##################################################################################

package:
  name: vcs
  version: "1.0.0"
    
build:
  number: 0
  script:
    - git config --system alias.co checkout
    - git config --system alias.br branch
    - git config --system alias.ci commit
    - git config --system alias.st status
    - git config --system alias.unstage 'reset HEAD --'
    - git config --system alias.last 'log -1 HEAD'
    - git config --system credential.helper 'cache --timeout=3600'
  always_include_files:
    - etc/gitconfig

about:
  home: http://statiskit.readthedocs.io/
  license: CeCILL-C

requirements:
  build:
    - git
  run:
    - git