package:
  name: mpfr
  version: "3.1.3"

source:
  fn: mpfr-3.1.3.tar.bz2
  url: http://www.mpfr.org/mpfr-3.1.3/mpfr-3.1.3.tar.bz2
  md5: 5fdfa3cfa5c86514ee4a241a1affa138

requirements:
  build:
    - gmp
  run:
    - gmp


about:
  home: http://www.mpfr.org/
  license: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
