package:
  name: mpfr
  version: "2.4.2"

source:
  fn: mpfr-2.4.2.tar.bz2
  url: ftp://gcc.gnu.org/pub/gcc/infrastructure/mpfr-2.4.2.tar.bz2

requirements:
  build:
    - gmp
  run:
    - gmp

about:
  home: http://www.mpfr.org/
  license: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
