package:
  name: libgcc
  version: "5.4.0"

source:
  fn: gcc-5.4.0.tar.bz2
  url: http://mirrors.kernel.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
  md5: 4c626ac2a83ef30dfb9260e6f59c2b30
  patches:
    - 0001-Libiberty-normalize-split-directories.patch

build:
  number: 2
  detect_binary_files_with_prefix: false

requirements:
  build:
    - gmp
    - mpfr
    - mpc
    - isl
    - binutils
    - linux-headers   [linux]
    #- gcc
    - glibc-dev
  run:
    - gmp
    - mpfr
    - mpc
    - isl
    - binutils
    - linux-headers   [linux]
    #- gcc
    - glibc-dev

  # always_include_files:
  #   - lib/libgcc_s.1.dylib # [osx]
  #   - lib/libgcc_s_ppc64.1.dylib # [osx]
  #   - lib/libgcc_s_x86_64.1.dylib # [osx]
  #   - lib/libgcc_s.so.1 # [linux]
  #   - lib/libgcc_s.so # [linux]

  #   - lib/libgomp.1.dylib # [osx]
  #   - lib/libgomp.dylib # [osx]
  #   - lib/libgomp.so # [linux]
  #   - lib/libgomp.so.1 # [linux]
  #   - lib/libgomp.so.1.0.0 # [linux]

  #   - lib/libgfortran.3.dylib # [osx]
  #   - lib/libgfortran.dylib # [osx]
  #   - lib/libgfortran.so # [linux]
  #   - lib/libgfortran.so.3 # [linux]
  #   - lib/libgfortran.so.3.0.0 # [linux]

  #   - lib/libquadmath.0.dylib # [osx]
  #   - lib/libquadmath.dylib # [osx]
  #   - lib/libquadmath.so # [linux]
  #   - lib/libquadmath.so.0 # [linux]
  #   - lib/libquadmath.so.0.0.0 # [linux]

  #   - lib/libstdc++.6.dylib # [osx]
  #   - lib/libstdc++.dylib # [osx]
  #   - lib/libstdc++.so # [linux]
  #   - lib/libstdc++.so.6 # [linux]
  #   - lib/libstdc++.so.6.0.21 # [linux]

about:
  home: http://gcc.gnu.org/
  summary: Shared libraries for the GNU Compiler Collection
  license: GPL
