{% set version = "0.28" %}

package:
  name: pkg-config
  version: {{ version }}

source:
  fn: pkg-config-{{ version }}.zip
  url: https://github.com/tpn/pkg-config/archive/pkg-config-{{ version }}.zip
  sha256: 81ec7beea5856664ecfe0f80c9ab3a87b1baf8a9b90cdf166a3d506c172a332e

build:
  skip: True  # [win]
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - zlib 1.2*
    - autoconf
    - python
    - automake
    - libtool
  run:
    - zlib 1.2*

test:
  commands:
    - pkg-config --help
    - '[ "$(pkg-config freetype2 --cflags)" == "-I$PREFIX/include/freetype2 " ]'

  requires:
    - freetype

about:
  home: http://www.freedesktop.org/wiki/Software/pkg-config/
  license: GPL 2
  summary: Interface for querying installed libraries for use during compilation.

extra:
  recipe-maintainers:
    - jakirkham
    - mdboom
    - ocefpaf
    - tacaswell
