# Adpated from https://github.com/conda/conda-recipes/tree/master/boost
package:
  name: python-parse
  version: 1.6.6

source:
  fn: parse-1.6.6.tar.gz
  url: https://pypi.python.org/packages/c3/e3/c2ca7f10c481b84ba7bf8c35c595ee4825d828fce7838fffc57f0ea0acc9/parse-1.6.6.tar.gz

build:
  number: 0

about:
  home: https://github.com/r1chardj0n3s/parse
  license: BSD license

requirements:
  build:
    - python
  run:
    - python
