##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (26)                       #
#                                                                                #
##################################################################################

package:
  name: libdev
  version: "1.0.0"
    
build:
  number: 0
  track_features:
    - vc9                  [win and py27]
    - vc10                 [win and py34]
    - vc14                 [win and py35]

about:
  home: http://statiskit.readthedocs.io/
  license: CeCILL
  
requirements:
  build:
    - python
    - python-scons
    - pywin32             [win]
    - vs2008_runtime      [win and py27]
    - vs2010_runtime      [win and py34]
    - vs2015_runtime      [win and py35]
  run:
    - python
    - python-scons
    - pywin32             [win]
    - vs2008_runtime      [win and py27]
    - vs2010_runtime      [win and py34]
    - vs2015_runtime      [win and py35]